spring.application.name=demo
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/request_demo
spring.datasource.username=postgres
spring.datasource.password=04041996As!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.file.name=app.log
logging.level.root=INFO